version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: connekt_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
    driver: local
