version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    container_name: connekt
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
    driver: local
